# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ca59f520f9121a36ea6d8632efe4e56bf6c8a667ae5528d32099231fa3cbc075dfc8d2404854a7dc8398fdabaf26dea63c9a2fa20770447bf1967ff7090a64

test:
  secret_key_base: 4c605258a762251cbe447c3e9fcfbb6aef7c1b87969c1daaabb6f0136942c420649c7741b3c756fde8942e0c873050289f85381bb6e2604e1a222dd72a0b2671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
